project:
  type: website

website:
  title: "Snippets of Things"
  navbar:
    right:
      - href: https://dmolitor.com
        text: "Home"
      - icon: github
        href: https://github.com/dmolitor/blog
    search: false
    pinned: true
  favicon: "media/_favicon.png"

format:
  html:
    mainfont: verdana
    theme: minty
    css: styles.css
